# Payload URLs
PAYLOAD_URLS = [
    "https://raw.githubusercontent.com/payloadbox/xss-payload-list/refs/heads/master/Intruder/xss-payload-list.txt",
    "https://raw.githubusercontent.com/cc1a2b/PenHunter/refs/heads/main/penhunter/payload/xor.txt",
    "https://raw.githubusercontent.com/cc1a2b/PenHunter/refs/heads/main/penhunter/payload/xss_advanced.txt",
    "https://raw.githubusercontent.com/cc1a2b/PenHunter/refs/heads/main/penhunter/payload/xss_more_advamced.txt",
    "https://raw.githubusercontent.com/cc1a2b/PenHunter/refs/heads/main/penhunter/payload/xss_payload.txt",
    "https://raw.githubusercontent.com/InfoSecWarrior/Offensive-Payloads/refs/heads/main/Cross-Site-Scripting-XSS-Payloads.txt",
    "https://raw.githubusercontent.com/Proviesec/xss-payload-list/refs/heads/main/xss-all-list.txt",
    "https://raw.githubusercontent.com/Proviesec/xss-payload-list/refs/heads/main/xss-by-keyword-filtering.txt",
    "https://raw.githubusercontent.com/Proviesec/xss-payload-list/refs/heads/main/xss-encoding-payload.txt",
    "https://raw.githubusercontent.com/Proviesec/xss-payload-list/refs/heads/main/xss-for-hidden-input.txt",
    "https://raw.githubusercontent.com/Proviesec/xss-payload-list/refs/heads/main/xss-for-input.txt",
    "https://raw.githubusercontent.com/Proviesec/xss-payload-list/refs/heads/main/xss-for-markdowns.txt",
    "https://raw.githubusercontent.com/Proviesec/xss-payload-list/refs/heads/main/xss-for-onfocus.txt",
    "https://raw.githubusercontent.com/Proviesec/xss-payload-list/refs/heads/main/xss-for-title.txt",
    "https://raw.githubusercontent.com/Proviesec/xss-payload-list/refs/heads/main/xss-for-username-field.txt",
    "https://raw.githubusercontent.com/Proviesec/xss-payload-list/refs/heads/main/xss-for-vuejs.txt",
    "https://raw.githubusercontent.com/Proviesec/xss-payload-list/refs/heads/main/xss-href.txt",
    "https://raw.githubusercontent.com/Proviesec/xss-payload-list/refs/heads/main/xss-payload-for-input-search.txt",
    "https://raw.githubusercontent.com/Proviesec/xss-payload-list/refs/heads/main/xss-polyglot.txt",
    "https://raw.githubusercontent.com/Proviesec/xss-payload-list/refs/heads/main/xss-top500-list.txt",
    "https://raw.githubusercontent.com/Proviesec/xss-payload-list/refs/heads/main/xss-without-alert-confirm-prompt",
    "https://raw.githubusercontent.com/Proviesec/xss-payload-list/refs/heads/main/xss-without-alert.txt",
    "https://gist.githubusercontent.com/mmssr/507cd83befa43b696e9f58344ecb4039/raw/7302feb198eda37d06df1641afb3267b6bf566e7/Simple%2520XSS%2520payloads",
    "https://raw.githubusercontent.com/1234567890291/xss-payload/refs/heads/main/payload.txt",
]
